version: '3'
services:
  shinobi-chronicles-db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - sc_db:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "nc -z 127.0.0.1 3306 || exit 1" ]
      interval: 1m30s
      timeout: 60s
      retries: 6
    hostname: shinobi-chronicles-db

  # Web DB Tool
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: shinobi-chronicles-db
      PMA_PORT: "3306"

  # PHP server
  web_server:
    build:
      dockerfile: docker/Dockerfile
      context: "."
      args:
        ENV: ${ENV}
        WEB_URL: ${WEB_URL}
        DB_HOST: shinobi-chronicles-db
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "80:80"
    image: shinobi_chronicles_web_app
    volumes:
      - ./:/var/www/html
    depends_on:
      - shinobi-chronicles-db

volumes:
  sc_db:
  sc_app: